events { 
    worker_connections 1024; 
}

http {
    # 1. Define the structured JSON template [1]
    # log_format json_analytics escape=json '{'
    #     '"time_local":"$time_local",'
    #     '"remote_addr":"$remote_addr",'
    #     '"request":"$request",'
    #     '"status": "$status",'
    #     '"body_bytes_sent":"$body_bytes_sent",'
    #     '"request_time":"$request_time",'
    #     '"http_referrer":"$http_referer",'
    #     '"http_user_agent":"$http_user_agent"'
    # '}';
    # Define your group of backend servers
    upstream my_backend_servers {
        least_conn; # <-- This turns on the Least Connections algorithm
        
        server server1:80;
        server server2:80;
        server server3:80;
    }

    server {
        listen 80; # Listen for incoming traffic on port 80

        location / {
            # Pass all incoming traffic to the backend group defined above
            proxy_pass http://my_backend_servers;
            
            proxy_set_header Host $host;
            proxy_set_header X-Real-IP $remote_addr;
        }
    }

    # Automatically redirect HTTP traffic (port 80) to HTTPS (port 443)
    server {
        listen 80;
        return 301 https://$host$request_uri;
    }

    # Secure HTTPS Server
    server {
        listen 443 ssl;
        
        access_log /dev/stdout json_analytics;

        # Paths inside the container where the certificates will live
        ssl_certificate /etc/nginx/ssl/nginx.crt;
        ssl_certificate_key /etc/nginx/ssl/nginx.key;

        location / {
            proxy_pass http://my_backend_servers;
            proxy_set_header Host $host;
            proxy_set_header X-Real-IP $remote_addr;
        }
    }
}
